version: "3.9"

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./server/scripts/db/init:/docker-entrypoint-initdb.d:ro"
    ports:
      - "5432:5432"

volumes:
  dbdata:
